package chinese.checkers.ui;

import chinese.checkers.Logic.Game;
import chinese.checkers.Models.Board.SimpleBoard;
import chinese.checkers.Models.LeaderBoard;
import chinese.checkers.Models.PlayerColor.PlayerColor;
import com.intellij.uiDesigner.core.GridConstraints;
import com.intellij.uiDesigner.core.GridLayoutManager;
import com.intellij.uiDesigner.core.Spacer;

import javax.swing.*;
import javax.swing.plaf.FontUIResource;
import javax.swing.text.StyleContext;
import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.Locale;
import java.util.function.Supplier;

public class Game_Window extends JFrame {
    private JPanel panelMain;
    private BoardPanel boardPanel;
    private SimpleBoard board;
    private Game game;
    private JButton reset;
    private JPanel boardContainer;
    private JButton newGameMode;
    private JLabel curTurn;
    private JLabel nextTurn;
    private JPanel leaderBoardPanel;
    private JLabel leaderBoardLabel;

    // FOR TESTING!
    private JButton forceWin;

    private final LeaderBoard leaderBoard;

    public void setCurTurn(String turn) {
        curTurn.setText("Current turn: " + turn);
    }

    public void setNextTurn(String turn) {
        nextTurn.setText("Next turn: " + turn);
    }

    public Game_Window(Supplier<SimpleBoard> typeBoard, LeaderBoard leaderBoard) {
        board = typeBoard.get();
        this.leaderBoard = leaderBoard;
        game = new Game(board, this.leaderBoard);
        boardPanel = new BoardPanel(board, game);

        boardContainer.setLayout(new BorderLayout());
        boardContainer.add(boardPanel, BorderLayout.CENTER);

        curTurn.setText("Current turn: " + game.getCurrentTurn());
        nextTurn.setText("Next turn: " + game.getNextTurn());

        updateLeaderBoardUI();

        this.setTitle("Китайские шашки");
        this.setContentPane(panelMain);
        this.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.setVisible(true);
        this.pack();

        this.setLocationRelativeTo(null);

        game.setOnTurnChanged(() -> {
            setCurTurn(game.getCurrentTurn());
            setNextTurn(game.getNextTurn());
        });

        game.setOnGameWon(winner -> {
            JOptionPane.showMessageDialog(
                    this,
                    "Player " + winner + " wins!",
                    "Game over",
                    JOptionPane.INFORMATION_MESSAGE
            );

            updateLeaderBoardUI();
            restartGame(board = typeBoard.get());
        });

        reset.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                board = typeBoard.get();

                restartGame(board);
            }
        });

        newGameMode.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                dispose();

                new ChooseGame();
            }
        });

        forceWin.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                game.forceWin(PlayerColor.BLUE);
                restartGame(typeBoard.get());
            }
        });
    }

    private void restartGame(SimpleBoard curBoard) {
        this.board = curBoard;

        game = new Game(board, leaderBoard);

        bindGame(game, curBoard);

        boardContainer.removeAll();
        boardPanel = new BoardPanel(board, game);
        boardContainer.add(boardPanel, BorderLayout.CENTER);

        boardContainer.revalidate();
        boardContainer.repaint();
    }

    private void bindGame(Game game, SimpleBoard curBoard) {
        game.setOnTurnChanged(() -> {
            setCurTurn(game.getCurrentTurn());
            setNextTurn(game.getNextTurn());
        });

        game.setOnGameWon(winner -> {
            JOptionPane.showMessageDialog(
                    this,
                    "Player " + winner + " wins!",
                    "Game over",
                    JOptionPane.INFORMATION_MESSAGE
            );
            updateLeaderBoardUI();
            restartGame(curBoard);
        });
    }

    private void updateLeaderBoardUI() {
        StringBuilder sb = new StringBuilder("<html>");

        sb.append("Leaderboard:<br><br>");

        leaderBoard.getBoard().forEach((color, wins) ->
                sb.append(color)
                        .append(": ")
                        .append(wins)
                        .append("<br>")
        );

        sb.append("</html>");
        leaderBoardLabel.setText(sb.toString());
    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        panelMain = new JPanel();
        panelMain.setLayout(new GridLayoutManager(6, 3, new Insets(0, 0, 0, 0), -1, -1));
        boardContainer = new JPanel();
        boardContainer.setLayout(new BorderLayout(0, 0));
        panelMain.add(boardContainer, new GridConstraints(0, 1, 6, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, null, null, null, 0, false));
        final Spacer spacer1 = new Spacer();
        panelMain.add(spacer1, new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_VERTICAL, 1, GridConstraints.SIZEPOLICY_WANT_GROW, null, null, null, 0, false));
        final JPanel panel1 = new JPanel();
        panel1.setLayout(new GridLayoutManager(2, 3, new Insets(0, 0, 0, 0), -1, -1));
        panelMain.add(panel1, new GridConstraints(1, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, null, null, null, 0, false));
        reset = new JButton();
        reset.setText("Reset");
        panel1.add(reset, new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, new Dimension(100, 60), new Dimension(100, 60), new Dimension(100, 60), 0, false));
        newGameMode = new JButton();
        newGameMode.setText("New Mode");
        panel1.add(newGameMode, new GridConstraints(1, 0, 1, 2, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, new Dimension(100, 60), new Dimension(100, 60), new Dimension(100, 60), 0, false));
        final Spacer spacer2 = new Spacer();
        panel1.add(spacer2, new GridConstraints(0, 1, 1, 2, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_WANT_GROW, 1, null, null, null, 0, false));
        final Spacer spacer3 = new Spacer();
        panel1.add(spacer3, new GridConstraints(1, 2, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_WANT_GROW, 1, null, null, null, 0, false));
        final Spacer spacer4 = new Spacer();
        panelMain.add(spacer4, new GridConstraints(5, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_VERTICAL, 1, GridConstraints.SIZEPOLICY_WANT_GROW, null, null, null, 0, false));
        curTurn = new JLabel();
        Font curTurnFont = this.$$$getFont$$$(null, -1, 24, curTurn.getFont());
        if (curTurnFont != null) curTurn.setFont(curTurnFont);
        curTurn.setText("Current turn: ");
        panelMain.add(curTurn, new GridConstraints(2, 0, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, new Dimension(400, -1), new Dimension(400, -1), new Dimension(400, -1), 0, false));
        nextTurn = new JLabel();
        Font nextTurnFont = this.$$$getFont$$$(null, -1, 24, nextTurn.getFont());
        if (nextTurnFont != null) nextTurn.setFont(nextTurnFont);
        nextTurn.setText("nextTurn turn: ");
        panelMain.add(nextTurn, new GridConstraints(3, 0, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, new Dimension(400, -1), new Dimension(400, -1), new Dimension(400, -1), 0, false));
        leaderBoardPanel = new JPanel();
        leaderBoardPanel.setLayout(new GridLayoutManager(1, 1, new Insets(0, 0, 0, 0), -1, -1));
        panelMain.add(leaderBoardPanel, new GridConstraints(0, 2, 6, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, null, null, null, 0, false));
        leaderBoardLabel = new JLabel();
        Font leaderBoardLabelFont = this.$$$getFont$$$(null, -1, 20, leaderBoardLabel.getFont());
        if (leaderBoardLabelFont != null) leaderBoardLabel.setFont(leaderBoardLabelFont);
        leaderBoardLabel.setText("Winners");
        leaderBoardPanel.add(leaderBoardLabel, new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, new Dimension(400, -1), new Dimension(400, -1), new Dimension(400, -1), 0, false));
        final JPanel panel2 = new JPanel();
        panel2.setLayout(new GridLayoutManager(1, 2, new Insets(0, 0, 0, 0), -1, -1));
        panelMain.add(panel2, new GridConstraints(4, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, null, null, null, 0, false));
        forceWin = new JButton();
        forceWin.setText("TEST");
        panel2.add(forceWin, new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        final Spacer spacer5 = new Spacer();
        panel2.add(spacer5, new GridConstraints(0, 1, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_WANT_GROW, 1, null, null, null, 0, false));
    }

    /**
     * @noinspection ALL
     */
    private Font $$$getFont$$$(String fontName, int style, int size, Font currentFont) {
        if (currentFont == null) return null;
        String resultName;
        if (fontName == null) {
            resultName = currentFont.getName();
        } else {
            Font testFont = new Font(fontName, Font.PLAIN, 10);
            if (testFont.canDisplay('a') && testFont.canDisplay('1')) {
                resultName = fontName;
            } else {
                resultName = currentFont.getName();
            }
        }
        Font font = new Font(resultName, style >= 0 ? style : currentFont.getStyle(), size >= 0 ? size : currentFont.getSize());
        boolean isMac = System.getProperty("os.name", "").toLowerCase(Locale.ENGLISH).startsWith("mac");
        Font fontWithFallback = isMac ? new Font(font.getFamily(), font.getStyle(), font.getSize()) : new StyleContext().getFont(font.getFamily(), font.getStyle(), font.getSize());
        return fontWithFallback instanceof FontUIResource ? fontWithFallback : new FontUIResource(fontWithFallback);
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return panelMain;
    }

}
